<a href="https://colab.research.google.com/github/JhonHendricksBautista/Bautista_CPE311/blob/main/CPE313_HOA8_1_Text_Similarity_Bautista%2CJhon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 5.1 Text Similarity

#### Objective(s):

This activity aims to introduce how to implement text similarity

#### Intended Learning Outcomes (ILOs):
* Demonstrate how to remove special characters from text
* Demonstrate how to measure text simiarity using distance
* Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

#### Resources:
* Jupyter Notebook
* songdata.csv

#### Procedures
Load the necessary libraries

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [60]:
import nltk
import pandas as pd

In [61]:
data = pd.read_csv('/content/drive/MyDrive/datasci3/songdata.csv')
data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nAnd it means something special to me \r\nLook at the way that she smiles when she sees me \r\nHow lucky can one fellow be? \r\n \r\nShe's just my kind of girl, she makes me feel fine \r\nWho could ever believe that she could be mine? \r\nShe's just my kind of girl, without her I'm blue \r\nAnd if she ever leaves me what could I do, what could I do? \r\n \r\nAnd when we go for a walk in the park \r\nAnd she holds me and squeezes my hand \r\nWe'll go on walking for hours and talking \r\nAbout all the things that we plan \r\n \r\nShe's just my kind of girl, she makes me feel fine \r\nWho could ever believe that she could be mine? \r\nShe's just my kind of girl, without her I'm blue \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gently like a summer evening breeze \r\nTake your time, make it slow \r\nAndante, Andante \r\nJust let the feeling grow \r\n \r\nMake your fingers soft and light \r\nLet your body be the velvet of the night \r\nTouch my soul, you know how \r\nAndante, Andante \r\nGo slowly with me now \r\n \r\nI'm your music \r\n(I am your music and I am your song) \r\nI'm your song \r\n(I am your music and I am your song) \r\nPlay me time and time again and make me strong \r\n(Play me again 'cause you're making me strong) \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\n \r\nThere's a shimmer in your eyes \r\nLike the feeling of a thousand butterflies \r\nPlease don't talk, go on, play \r\nAndante, Andante \r\nAnd let me float away \r\n \r\nI'm your music \r\n(I am your music and I am your song) \r\nI'm your song \r\n(I am your music and I am your song) \r\nPlay me time and time again and make me strong \r\n(Play me again 'cause you're making me strong) \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\n \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\nAndante, Andante \r\nOh please don't let me down\r\n\r\n"
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,"I'll never know why I had to go \r\nWhy I had to put up such a lousy rotten show \r\nBoy, I was tough, packing all my stuff \r\nSaying I don't need you anymore, I've had enough \r\nAnd now, look at me standing here again 'cause I found out that \r\nMa ma ma ma ma ma ma ma ma ma ma ma ma ma ma ma my life is here \r\nGotta have you near \r\n \r\nAs good as new, my love for you \r\nAnd keeping it that way is my intention \r\nAs good as new and growing too \r\nYes, I think it's taking on a new dimension \r\nIt's as good as new, my love for you \r\nJust like it used to be and even better \r\nAs good as new, thank God it's true \r\nDarling, we were always meant to stay together \r\n \r\nFeel like a creep, never felt so cheap \r\nNever had a notion that my love could be so deep \r\nHow could I make such a dumb mistake \r\nNow I know I'm not entitled to another break \r\nBut please, baby, I beg you to forgive 'cause I found out that \r\nMa ma ma ma ma ma ma ma ma ma ma ma ma ma ma ma my life is here \r\nGotta get you near \r\n \r\nI thought that our love was at an end but here I am again \r\n \r\nAs good as new, my love for you \r\nAnd keeping it that way is my intention \r\nAs good as new and growing too \r\nYes, I think it's taking on a new dimension \r\nIt's as good as new, my love for you \r\nJust like it used to be and even better \r\nAs good as new, thank God it's true \r\nDarling, we were always meant to stay together \r\n \r\nYes the love I have for you feels as good as new \r\nDarling, we were always meant to stay together\r\n\r\n"
3,ABBA,Bang,/a/abba/bang_20598415.html,"Making somebody happy is a question of give and take \r\nYou can learn how to show it so come on, give yourself a break \r\nEvery smile and every little touch \r\nDon't you know that they mean so much \r\nSweet sweet kisses so tender \r\nAlways will return to sender \r\n \r\nLike a bang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nSo give it away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love \r\n \r\nLove is always around and you can look for it anywhere \r\nWhen you feel that you've found it my advice is to take good care \r\nNever use it as a selfish tool \r\nNever ever be such a fool \r\nEvery feeling you're showing \r\nIs a boomerang you're throwing \r\n \r\nYes a bang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nSo give it away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\n \r\nAnd if you're warm and tender \r\nI'll kiss you, return to sender \r\nPlease surrender \r\n \r\nBang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love\r\n\r\n"
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,"Making somebody happy is a question of give and take \r\nYou can learn how to show it so come on, give yourself a break \r\nEvery smile and every little touch \r\nDon't you know that they mean so much \r\nSweet sweet kisses so tender \r\nAlways will return to sender \r\n \r\nLike a bang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nBy giving away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love \r\n \r\nLove is always around and you can look for it anywhere \r\nWhen you feel that you've found it my advice is to take good care \r\nNever use it as a selfish tool \r\nNever ever be such a fool \r\nEvery feeling you're showing \r\nIs a boomerang you're throwing \r\n \r\nYes a bang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nBy giving away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\n \r\nAnd if you're warm and tender \r\nI'll kiss you, return to sender \r\nPlease surrender \r\n \r\nBang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love\r\n\r\n"

Find the lyrics by the artist The Beatles

In [62]:
beatles = data[data.artist=='The Beatles']
beatles.head()

,artist,song,link,text
1198,The Beatles,A Shot Of Rhythm And Blues,/b/beatles/a+shot+of+rhythm+blues_20014867.html,"Well, if your hands start a-clappin' \r\nAnd your fingers start a-poppin' \r\nAnd your feet start a-movin' around \r\nAnd if you start to swing and sway \r\n \r\nWhen the band starts to play \r\nA real cool way out sound \r\nAnd if you get to can't help it and you can't sit down \r\nYou feel like you gotta move around \r\n \r\nYou get a shot of rhythm and blues. \r\nWith just a little rock and roll on the side \r\nJust for good measure. \r\nGet a pair of dancin' shoes \r\n \r\nWell, with your lover by your side \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\n \r\nAnd chills come up on you \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\n \r\nGet a shot of rhythm and blues \r\nWith just a little rock and roll on the side \r\nJust for good measure \r\nGet a pair of dancin' shoes \r\n \r\nWell, with your lover by your side \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\n \r\nAnd chills come up on you \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\n \r\nGet a shot of rhythm and blues \r\nGet a pair of dancin' shoes \r\nGet a shot of rhythm and blues \r\nWell, with your lover by your side \r\n \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\nAnd chills come up on you \r\n \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\nWell, here's something for you to do \r\nWell, here's something for you to do\r\n\r\n"
1199,The Beatles,Across The Universe,/b/beatles/across+the+universe_10026507.html,"Words are flowing out like \r\nEndless rain into a paper cup \r\nThey slither wildly as they slip away across the universe. \r\nPools of sorrow waves of joy \r\nAre drifting through my opened mind \r\nPossessing and caressing me. \r\n \r\nJai Guru Deva. Om \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nImages of broken light, which \r\nDance before me like a million eyes, \r\nThey call me on and on across the universe. \r\nThoughts meander like a \r\nRestless wind inside a letter box \r\nThey tumble blindly as they make their way across the universe. \r\n \r\nJai Guru Deva. Om \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nSounds of laughter, shades of life \r\nAre ringing through my opened ears \r\nInciting and inviting me. \r\nLimitless undying love, which \r\nShines around me like a million suns, \r\nIt calls me on and on across the universe \r\n \r\nJai Guru Deva, om. \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva\r\n\r\n"
1200,The Beatles,All I've Got To Do,/b/beatles/all+ive+got+to+do_10026646.html,"Whenever I want you around, yeah \r\nAll I gotta do \r\nIs call you on the phone \r\nAnd you'll come running home, yeah \r\nThat's all I gotta do. \r\n \r\nAnd when I, I wanna kiss you, yeah \r\nAll I gotta do \r\nIs whisper in your ear \r\nThe words you long to hear \r\nAnd I'll be kissing you \r\n \r\nAnd the same goes for me \r\nWhenever you want me at all \r\nI'll be here yes I will \r\nWhenever you call \r\nYou just gotta call on me, yeah \r\nYou just gotta call on me \r\n \r\nAnd when I, I wanna kiss you, yeah \r\nAll I got to do \r\nIs call you on the phone \r\nAnd you'll come running home, yeah \r\nThat's all I gotta do. \r\n \r\nAnd the same goes for me \r\nWhenever you want me at all \r\nI'll be here, yes I will \r\nWhenever you call \r\nYou just gotta call on me \r\nYou just gotta call on me. \r\n \r\nOh, you just gotta call on me\r\n\r\n"
1201,The Beatles,And I Love Her,/b/beatles/and+i+love+her_10026463.html,"I give her all my love \r\nThat's all I do \r\nAnd if you saw my love \r\nYou'd love her to \r\nI love her \r\n \r\nShe gives my everything \r\nAnd tenderly \r\nThe kiss my lover brings \r\nShe brings to me \r\nAnd I love her \r\n \r\nA love like ours \r\nCould never die \r\nAs long as I \r\nHave you near me \r\n \r\nBright are the stars that shine \r\nDark is the sky \r\nI know this love of mine \r\nWill never die \r\nAnd I love her \r\n \r\nBright are the stars that shine \r\nDark is the sky \r\nI know this love of mine \r\nWill never die \r\nAnd I love her, ooh\r\n\r\n"
1202,The Beatles,And Your Bird Can Sing,/b/beatles/and+your+bird+can+sing_10026364.html,"You tell me that you've got everything you want \r\nAnd your bird can sing \r\nBut you don't get me \r\nYou don't get me \r\n \r\nYou say you've seen the seven wonders \r\nAnd you bird is green \r\nBut you can't see me \r\nYou can't see me \r\n \r\nWhen your prized possessions \r\nStart to weigh you down \r\nLook in my direction \r\nI'll be round, I'll be round \r\n \r\nWhen your bird is broken \r\nWill it bring you down \r\nYou may be awoken \r\nI'll be round, I'll be round \r\n \r\nYou tell me that you've heard every sound there is \r\nAnd your bird can swing \r\nBut you can't hear me \r\nYou can't hear me\r\n\r\n"

Check the number of Beatles songs in the data set

In [63]:
data.artist.value_counts().loc[['The Beatles']]

artist
The Beatles    178
Name: count, dtype: int64

Take a look at the first song's lyrics

In [64]:
beatles.iloc[0,3]

"Well, if your hands start a-clappin'  \r\nAnd your fingers start a-poppin'  \r\nAnd your feet start a-movin' around  \r\nAnd if you start to swing and sway  \r\n  \r\nWhen the band starts to play  \r\nA real cool way out sound  \r\nAnd if you get to can't help it and you can't sit down  \r\nYou feel like you gotta move around  \r\n  \r\nYou get a shot of rhythm and blues.  \r\nWith just a little rock and roll on the side  \r\nJust for good measure.  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nWith just a little rock and roll on the side  \r\nJust for good measure  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nGet a pair of dancin' shoes  \r\nGet a shot of rhythm and blues  \r\nWell, with your lover by your side  \r\n  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\nAnd chills come up on you  \r\n  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do\r\n\r\n"

Remove characters from the lyrics

In [65]:
import re

newline = lambda x: re.sub('\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub('\w*\d\w*', ' ', x) # remove alphanumeric words

corpus = beatles.text.map(newline).map(alphanumeric)
corpus.head()

<>:4: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_2563/2279837142.py:4: SyntaxWarning: invalid escape sequence '\w'
  alphanumeric = lambda x: re.sub('\w*\d\w*', ' ', x) # remove alphanumeric words

1198    Well, if your hands start a-clappin'  \r And your fingers start a-poppin'  \r And your feet start a-movin' around  \r And if you start to swing and sway  \r   \r When the band starts to play  \r A real cool way out sound  \r And if you get to can't help it and you can't sit down  \r You feel like you gotta move around  \r   \r You get a shot of rhythm and blues.  \r With just a little rock and roll on the side  \r Just for good measure.  \r Get a pair of dancin' shoes  \r   \r Well, with your lover by your side  \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r   \r And chills come up on you  \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r   \r Get a shot of rhythm and blues  \r With just a little rock and roll on the side  \r Just for good measure  \r Get a pair of dancin' shoes  \r   \r Well, with your lover by your side  \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r   \r And chills come up on you  \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r   \r Get a shot of rhythm and blues  \r Get a pair of dancin' shoes  \r Get a shot of rhythm and blues  \r Well, with your lover by your side  \r   \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r And chills come up on you  \r   \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r Well, here's something for you to do  \r Well, here's something for you to do\r \r
1199                                                                                                                                                                                                                                                                                                                                                                                                                                         Words are flowing out like  \r Endless rain into a paper cup  \r They slither wildly as they slip away across the universe.  \r Pools of sorrow waves of joy  \r Are drifting through my opened mind  \r Possessing and caressing me.  \r   \r Jai Guru Deva. Om  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Images of broken light, which  \r Dance before me like a million eyes,  \r They call me on and on across the universe.  \r Thoughts meander like a  \r Restless wind inside a letter box  \r They tumble blindly as they make their way across the universe.  \r   \r Jai Guru Deva. Om  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Sounds of laughter, shades of life  \r Are ringing through my opened ears  \r Inciting and inviting me.  \r Limitless undying love, which  \r Shines around me like a million suns,  \r It calls me on and on across the universe  \r   \r Jai Guru Deva, om.  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva\r \r
1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Whenever I want you around, yeah  \r All I gotta do  \r Is call you on the phone  \r And you'll come running home, yeah  \r That's all I gotta do.  \r   \r And when I, I wanna kiss you, yeah  \r All I gotta do  \r Is whisper in your ear  \r The words you long to hear  \r And I'll be kissing you  \r   \r And the same goes for me  \r Whenever you want me at all  \r I'll be here yes I will  \r Whenever you call  \r You just gotta call on me, yeah  \r You just gotta call on me  \r   \r And when I, I wanna kiss you, yeah  \r All I got to do  \r Is call you on the phone  \r And you'll come running home, yeah  \r That's all I gotta do.  \r   \r And the same goes for me  \r Whenever you want me at all  \r I'll be here, yes I will  \r Whenever you call  \r You just gotta call on me  \r You just gotta call on me.  \r   \r Oh, you just gotta call on me\r \r
1201                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I give her all my love  \r That's all I do  \r And if you saw my love  \r You'd love her to  \r I love her  \r   \r She gives my everything  \r And tenderly  \r The kiss my lover brings  \r She brings to me  \r And I love her  \r   \r A love like ours  \r Could never die  \r As long as I  \r Have you near me  \r   \r Bright are the stars that shine  \r Dark is the sky  \r I know this love of mine  \r Will never die  \r And I love her  \r   \r Bright are the stars that shine  \r Dark is the sky  \r I know this love of mine  \r Will never die  \r And I love her, ooh\r \r
1202                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         You tell me that you've got everything you want  \r And your bird can sing  \r But you don't get me  \r You don't get me  \r   \r You say you've seen the seven wonders  \r And you bird is green  \r But you can't see me  \r You can't see me  \r   \r When your prized possessions  \r Start to weigh you down  \r Look in my direction  \r I'll be round, I'll be round  \r   \r When your bird is broken  \r Will it bring you down  \r You may be awoken  \r I'll be round, I'll be round  \r   \r You tell me that you've heard every sound there is  \r And your bird can swing  \r But you can't hear me  \r You can't hear me\r \r
Name: text, dtype: object

Create a document term matrix using Count Vectorizer with the stop words turned on to English

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X, columns=cv.get_feature_names_out())
dt = dt.set_index(beatles.song)

dt.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Across The Universe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
All I've Got To Do,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
And I Love Her,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
And Your Bird Can Sing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Set display options so that the lyrics aren't cut off

In [67]:
pd.set_option('display.max_colwidth', None)

In [68]:
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

Imagine lyrics in Count Vectorizer form

In [69]:
imagine = list(dt.loc['Imagine'])
imagine[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Define the cosine similarity calculation

In [70]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

Calculate all similarities and sort by the most similar

In [71]:
similarity = [cosine(imagine, song) for song in X]
sorted(list(zip(similarity, beatles.song)), reverse=True)[1:6]

[(np.float64(0.22757944185316942), "I'll Cry Instead"),
 (np.float64(0.1738270040532526), 'In My Life'),
 (np.float64(0.16574838603294895), 'Eleanor Rigby'),
 (np.float64(0.1490280831849844), 'In Spite Of All The Danger'),
 (np.float64(0.14592261028699943), 'All My Loving')]

Create the TF-IDF Vectorizer

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Calculate all similarities and sort by the most similar using the TF-IDF data

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Compare the lyrics of Imagine and I'll Cry Instead

In [75]:
# Imagine lyrics
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

In [76]:
beatles[beatles.song=='I\'ll Cry Instead'].text

24774    I've got every reason on earth to be mad  \r\n'Cause I just lost the only girl I had  \r\nIf I could get my way  \r\nI'd get myself locked up today  \r\nBut I can't, so I'll cry instead  \r\n  \r\nI've got a chip on my shoulder that's bigger that my feet  \r\nI can't talk to people that I meet  \r\nIf I could see you now  \r\nI'd try to make you sad somehow  \r\nBut I can't, so I'll cry instead  \r\n  \r\nDon't want to cry when there's people there  \r\nI get shy when they start to stare  \r\nI'm gonna hide myself away  \r\nBut I'll come back again someday  \r\n  \r\nAnd when you do you'd better hide all the girls  \r\nI'm gonna break their hearts all round the world  \r\nYes, I'm gonna break them in two  \r\nAnd show you what your lovin' man can do  \r\nUntil then I'll cry instead\r\n\r\n
Name: text, dtype: object

Compare the two lyrics based on the output

In [77]:
# Extract TF-IDF vectors by song name
vec_imagine = dt_tfidf.loc['Imagine'].values
vec_cry = dt_tfidf.loc["I'll Cry Instead"].values

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([vec_imagine], [vec_cry])[0][0]
print("Cosine Similarity between 'Imagine' and 'I'll Cry Instead':", similarity)

Cosine Similarity between 'Imagine' and 'I'll Cry Instead': 0.13920289139351325

***Based on the cosine comparison, the two songs have a 0.13 similarity. This means the two songs has a low similarity even if they are made by the same band.***

#type your answer here

Find the two Beatles songs that are the most similar
* Using Count Vectorizer
* Using TF-IDF Vectorizer

Calculate the cosine similarity between all combinations of documents

In [79]:

from itertools import combinations

pairs = list(combinations(beatles.song.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(beatles)), 2)) # all index combos starting with (0,1)
song_pairs = [(beatles.song[a_index], beatles.song[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('A Shot Of Rhythm And Blues', 'Across The Universe'),
 ('A Shot Of Rhythm And Blues', "All I've Got To Do"),
 ('A Shot Of Rhythm And Blues', 'And I Love Her'),
 ('A Shot Of Rhythm And Blues', 'And Your Bird Can Sing'),
 ('A Shot Of Rhythm And Blues', 'Another Girl')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [80]:

results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8548876342047523), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.8359173188630292),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.8058125835571367), ('And I Love Her', 'Love Me Do')),
 (np.float64(0.7930110315846619), ('If I Fell', 'Love Me Do')),
 (np.float64(0.7478391382739419), ('And I Love Her', 'All You Need Is Love'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [81]:

results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8717047783261522),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.6599353568343105), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.6502842517883831), ('Have A Banana!', 'Crinsk Dee Night')),
 (np.float64(0.6232797327325461), ("Don't Let Me Down", 'Let It Be')),
 (np.float64(0.5275364336322863), ('If I Fell', 'Love Me Do'))]

In [82]:

beatles[beatles.song=='All You Need Is Love'].text

24695    Love, love, love, love, love, love, love, love, love.  \r\n  \r\nThere's nothing you can do that can't be done.  \r\nNothing you can sing that can't be sung.  \r\nNothing you can say, but you can learn  \r\nHow to play the game  \r\nIt's easy.  \r\nNothing you can make that can't be made.  \r\nNo one you can save that can't be saved.  \r\nNothing you can do, but you can learn  \r\nHow to be you in time  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nLove, love, love, love, love, love, love, love, love.  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\n  \r\nThere's nothing you can know that isn't known.  \r\nNothing you can see that isn't shown.  \r\nThere's nowhere you can be that isn't where  \r\nYou're meant to be  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nAll you need is love. (All together now).  \r\nAll you need is love. (Everybody).  \r\nAll you need is love, love. Love is all you need.  \r\nLove is all you need.  \r\nLove is all you need  \r\n  \r\n(Yesterday)  \r\n(Oh yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(Oh, yesterday)\r\n\r\n
Name: text, dtype: object

In [83]:
beatles[beatles.song=='Love Me Do'].text

24805    Love, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nSomeone to love,  \r\nSomebody new.  \r\nSomeone to love,  \r\nSomeone like you.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\nYeah, love me do.  \r\nWhoa, oh, love me do.\r\n\r\n
Name: text, dtype: object

In [84]:
beatles[beatles.song=='If I Needed Someone'].text

24768    If I needed someone to love  \r\nYou're the one that I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah, ah, ah  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah\r\n\r\n
Name: text, dtype: object

In [85]:
beatles[beatles.song=='If I Needed Someone To Love'].text

24769    If I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nIf I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone\r\n\r\n
Name: text, dtype: object

In [86]:
beatles[beatles.song=='Have A Banana!'].text

1221    [Speech]  \r\n  \r\nBrian Matthew: Is that it? Is that the end?  \r\nPaul: Yeah, yeah, that's it.  \r\nJohn: Fade, fade!  \r\nBrian: Good track. Oh, well, we'll stop there, stop there, stop there.  \r\nJohn: What an end!  \r\nBrian: Quiet! All right, George.  \r\nJohn: Fade!  \r\nBrian: Hold it!  \r\nGeorge: Oh, thank you.  \r\nJohn: Fade, you silly.  \r\nBrian: Well, we did. We did that. Oh, no! No! We've done that bit!  \r\nJohn: The train comes in now.  \r\nBrian: We did that.  \r\nJohn: Yeah.  \r\nBrian: To pove we weren't playing the record, then, you see. 'Cause,\r\notherwise, there's no point in you being here, is there? Ha, ha, ha!  \r\nJohn: Yeah, we did that, 'cause it sounds just like it, don't it?  \r\nBrian: Pretty cool lot of fellows, aren't you? Here, Ringo, have a banana,\r\ncatch!\r\n\r\n
Name: text, dtype: object

In [87]:
beatles[beatles.song=='Crinsk Dee Night'].text

24713    [Speech]  \r\n  \r\nBrian Matthew: The next few minutes, we're in the lap of the gods and the\r\nhands of the Beatles. In my young days, when I was a lad, they used to have\r\nactors in films and now that they--  \r\nPaul: Yes?  \r\nJohn: Hey! Listen!  \r\nPaul: It's all changed, now, Brian. They're not doing that, no actors.  \r\nJohn: It's all changed, now.  \r\nBrian: But this is what I wonder. In those days, the actors used to say their\r\nbest bits were left on the cutting room floor. Did you find that?  \r\nJohn: No, no, no, those were the good bits in the film. You should have seen\r\nthe rest.  \r\nBrian: Yes?  \r\nJohn: Rubbish!  \r\nBrian: Was it, really?  \r\nJohn: Even worse, yes.  \r\nBrian: Who was worst?  \r\nJohn: Oh, Paul.  \r\nBrian: I see.  \r\nPaul: I think John was about the worst.  \r\nJohn: No, it was you.  \r\nPaul: Oh, Ringo was very good. He was. He's a good lad.  \r\nBrian: He was. They're saying he's a new Charlie Chaplin. Do you think that's\r\nright?  \r\nJohn: He was miming.  \r\nPaul: You, too, with Jason.  \r\nJohn: Oh, yes, he's an old one. Okay, Ring?  \r\nBrian: Beginning to look like that. Now, then--  \r\nRingo: All right, John. Can you hear me?  \r\nPaul: Can you hear him? Hello!  \r\nBrian: Not really. I hope not. I hope not!  \r\nJohn: We brought you the flowers, Ring.  \r\nBrian: He's not allowed to talk.  \r\nRingo: Eh?  \r\nJohn: We brought you the flowers.  \r\nRingo: Oh, good.  \r\nJohn: And the grapes.  \r\nRingo: Oh, I like grapes.  \r\nPaul: He likes grapes.  \r\nGeorge: We've been to Portugal.  \r\nBrian: Guess who's, guess who's top of the pops in Portugal, then.  \r\nAll: Who?  \r\nBrian: Los Beatles.  \r\nJohn: Los Beatles? Great, great laugh.  \r\nBrian: I don't suppose you know the title of your film in Portuguese?  \r\nJohn: No. Crinsk dee Night?  \r\nBrian: Could be. Let's hear the number, shall we?  \r\nJohn: Right\r\n\r\n
Name: text, dtype: object

Compare the results. Which Vectorizer seems to do a better job?

***Based on the results the TF-IDf has provided a better similarity comparison because the output showed one clear similarity among the pair of songs. The TF-IDF was able to evaluate the tokens for the songs with better Compared to the Count Vector it shows that most of the pair of songs has similarity which may tell us the this process has not extracted or treated the important tokens with proper weights.***

#type your answer here

#### Supplementary Activity

* Use a dataset that consists of text document
* Remove special characters
* Compare the similar document using Count Vector and TF-IDF Vectorizer
* Use the cosine similarity to measure the similarity of text

## Use a dataset that consists of text document

In [88]:
#type your code here
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

df = pd.read_csv('/content/drive/MyDrive/datasci3/text_class.csv')
df.head(20)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Budget to set scene for election\n \n Gordon Brown will seek to put the economy at the centre of Labour's bid for a third term in power when he delivers his ninth Budget at 1230 GMT. He is expected to stress the importance of continued economic stability, with low unemployment and interest rates. The chancellor is expected to freeze petrol duty and raise the stamp duty threshold from Â£60,000. But the Conservatives and Lib Dems insist voters face higher taxes and more means-testing under Labour.\n \n Treasury officials have said there will not be a pre-election giveaway, but Mr Brown is thought to have about Â£2bn to spare.\n \n - Increase in the stamp duty threshold from Â£60,000 \n  - A freeze on petrol duty \n  - An extension of tax credit scheme for poorer families \n  - Possible help for pensioners The stamp duty threshold rise is intended to help first time buyers - a likely theme of all three of the main parties' general election manifestos. Ten years ago, buyers had a much greater chance of avoiding stamp duty, with close to half a million properties, in England and Wales alone, selling for less than Â£60,000. Since then, average UK property prices have more than doubled while the starting threshold for stamp duty has not increased. Tax credits As a result, the number of properties incurring stamp duty has rocketed as has the government's tax take. The Liberal Democrats unveiled their own proposals to raise the stamp duty threshold to Â£150,000 in February.\n \n The Tories are also thought likely to propose increased thresholds, with shadow chancellor Oliver Letwin branding stamp duty a "classic Labour stealth tax". The Tories say whatever the chancellor gives away will be clawed back in higher taxes if Labour is returned to power. Shadow Treasury chief secretary George Osborne said: "Everyone who looks at the British economy at the moment says there has been a sharp deterioration in the public finances, that there is a black hole," he said. "If Labour is elected there will be a very substantial tax increase in the Budget after the election, of the order of around Â£10bn."\n \n But Mr Brown's former advisor Ed Balls, now a parliamentary hopeful, said an examination of Tory plans for the economy showed there would be a Â£35bn difference in investment by the end of the next parliament between the two main parties. He added: "I don't accept there is any need for any changes to the plans we have set out to meet our spending commitments."\n \n For the Lib Dems David Laws said: "The chancellor will no doubt tell us today how wonderfully the economy is doing," he said. "But a lot of that is built on an increase in personal and consumer debt over the last few years - that makes the economy quite vulnerable potentially if interest rates ever do have to go up in a significant way." SNP leader Alex Salmond said his party would introduce a Â£2,000 grant for first time buyers, reduce corporation tax and introduce a citizens pension free from means testing. Plaid Cymru's economics spokesman Adam Price said he wanted help to get people on the housing ladder and an increase in the minimum wage to Â£5.60 an hour.\n
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Army chiefs in regiments decision\n \n Military chiefs are expected to meet to make a final decision on the future of Scotland's Army regiments.\n \n A committee of the Army Board, which is made up of the most senior defence figures, will discuss plans for restructuring regiments on Monday. The proposals include cutting Scotland's six single-battalion regiments to five and merging these into a super regiment. The plans have faced stiff opposition from campaigners and politicians alike. The committee's decision must be ratified by Defence Secretary Geoff Hoon and Prime Minister Tony Blair. It is expected that it will be made public next week. When ministers announced a reorganisation of the Army it drew a question mark over the futures of the Black Watch, the Kings Own Scottish Borderers, the Royal Scots, the Royal Highland Fusiliers and the Argyll and Sutherland Highlanders. In October, the Council of Scottish Colonels proposed the merger of the Royal Scots and the King's Own Scottish Borderers into a single battalion.\n \n Under their vision, it would be one of five in the new super regiment. The proposals to either merge or amalgamate the six regiments into a super regiment sparked a political outcry, with Labour backbenchers and opposition politicians opposing the plan. They felt the timing was insensitive because the Black Watch was in the frontline in Iraq, suffering casualties. The Save the Scottish Regiments campaigners were so angered they threatened to stand against Labour at the next general election.\n \n Speaking ahead of the expected Army Board meeting, a spokesman said: "The government and the Army Board have spent the past four months attempting to trick serving soldiers and the public into thinking their planned changes for the Scottish regiments are for the good of the Army and for that of the serving soldier. "They are very much not for the good and will destroy Scotland's regiments by moulding them into a single super regiment which will lead to severe recruitment problems, a loss of local connections to those regiments and a loss to Scotland of an important part of her heritage and, most importantly, her future - the regiments are the envy of armies around the world." An alternative blueprint had been put forward by Labour MP Eric Joyce, who proposed going ahead with the merger while preserving the other regiments. For a brief time, there was speculation the prime minister might consider the plan, but that now seems unlikely. Speaking in Scotland last week, Mr Blair said the aim was to preserve tradition but introduce a more effective structure and hinted that a super regiment was likely. He said: "They don't want to get rid of the history or the traditions of the regiment or the local connections - far from it, all they want to do is make sure they can transfer people easily across regiments and deploy them more flexibly." The prime minister said he hoped campaigners' concerns would be taken into account but the need for effective change had to be paramount.\n
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Howard denies split over ID cards\n \n Michael Howard has denied his shadow cabinet was split over its decision to back controversial Labour plans to introduce ID cards.\n \n The Tory leader said his front bench team had reached a "collective view" after holding a "good discussion", but admitted it was "not an easy issue". He had decided to support the plans as the police said they would help fight terror, crime and illegal immigration. The Lib Dems have pledged to oppose the bill when it is debated next Monday.\n \n Tory sources say senior party figures had argued vociferously against the ID card scheme. Among those reported to have serious reservations over the strategy were senior shadow cabinet members David Davis, Oliver Letwin and Tim Yeo. But Mr Howard denied Mr Yeo, his transport and environment spokesman, said the plans "stink". He also said he was confident shadow home secretary Mr Davis would "set out the position very clearly" when he stands up to debate the matter next week. Mr Howard said the police had said ID cards could "help them foil a terror bomb plot in which people could lose their lives". He added: "When the police say that you have to take them seriously".\n \n He acknowledged there were "good libertarian arguments" against the cards, but said the shadow Cabinet had weighed up all the "conflicting interests" before reaching its decision. "I don't pretend that it is an easy decision but at the end of the day a decision has to be taken." He also denied he was afraid of looking "soft" on the issue, compared to Labour. The Conservatives announced their support for the government plans on Monday evening.\n \n Sources within the party told the BBC Mr Howard had always been in favour of ID cards, and tried to introduce them when he was Home Secretary. But the Tories insisted they would hold ministers to account over the precise purpose of the scheme.\n \n They said they would also press Labour over whether objectives could be met and whether the Home Office would be able to deliver them. And they pledged to assess the cost effectiveness of ID cards and whether people's privacy would be properly protected. "It is important to remember that this bill will take a decade to come into full effect," a spokesman said. Lib Dem home affairs spokesman Mark Oaten has branded the ID scheme a waste of money and "deeply flawed". He said: "This has all the signs of Michael Howard overruling colleagues' concerns over ID cards."\n \n The chairman of the Bar Council, Guy Mansfield QC warned there was a real risk that people on the "margins of society" would be driven into the hands of extremists. "What is going to happen to young Asian men when there has been a bomb gone off somewhere? They are going to be stopped. If they haven't [ID cards] they are going to be detained." Tory ex-minister Douglas Hogg said he opposed the plans for ID cards branding them a "regressive" step which would intrude into the lives of ordinary citizens without any counterbalancing benefits. He predicted ultimately carrying the cards would become compulsory and that would lead to large numbers of Britain's ethnic minorities being stopped by police.\n

## PREPROCESSING

Tokenize (words)

In [89]:
# Tokenize words (just split by whitespace)
df['tokens_basic'] = df['Text'].apply(lambda x: x.split())
df['tokens_basic'].head()

0                                         [Budget, to, set, scene, for, election, Gordon, Brown, will, seek, to, put, the, economy, at, the, centre, of, Labour's, bid, for, a, third, term, in, power, when, he, delivers, his, ninth, Budget, at, 1230, GMT., He, is, expected, to, stress, the, importance, of, continued, economic, stability,, with, low, unemployment, and, interest, rates., The, chancellor, is, expected, to, freeze, petrol, duty, and, raise, the, stamp, duty, threshold, from, Â£60,000., But, the, Conservatives, and, Lib, Dems, insist, voters, face, higher, taxes, and, more, means-testing, under, Labour., Treasury, officials, have, said, there, will, not, be, a, pre-election, giveaway,, but, Mr, Brown, is, thought, ...]
1    [Army, chiefs, in, regiments, decision, Military, chiefs, are, expected, to, meet, to, make, a, final, decision, on, the, future, of, Scotland's, Army, regiments., A, committee, of, the, Army, Board,, which, is, made, up, of, the, most, senior, defence, figures,, will, discuss, plans, for, restructuring, regiments, on, Monday., The, proposals, include, cutting, Scotland's, six, single-battalion, regiments, to, five, and, merging, these, into, a, super, regiment., The, plans, have, faced, stiff, opposition, from, campaigners, and, politicians, alike., The, committee's, decision, must, be, ratified, by, Defence, Secretary, Geoff, Hoon, and, Prime, Minister, Tony, Blair., It, is, expected, that, it, will, be, made, public, ...]
2                                                [Howard, denies, split, over, ID, cards, Michael, Howard, has, denied, his, shadow, cabinet, was, split, over, its, decision, to, back, controversial, Labour, plans, to, introduce, ID, cards., The, Tory, leader, said, his, front, bench, team, had, reached, a, "collective, view", after, holding, a, "good, discussion",, but, admitted, it, was, "not, an, easy, issue"., He, had, decided, to, support, the, plans, as, the, police, said, they, would, help, fight, terror,, crime, and, illegal, immigration., The, Lib, Dems, have, pledged, to, oppose, the, bill, when, it, is, debated, next, Monday., Tory, sources, say, senior, party, figures, had, argued, vociferously, against, the, ID, ...]
3       [Observers, to, monitor, UK, election, Ministers, will, invite, international, observers, to, check, the, forthcoming, UK, general, election, is, fairly, run., The, move, comes, amid, claims, the, poll, could, be, marred, by, electoral, fraud., A, report, by, two, MPs, committees, called, on, Thursday, for, urgent, changes, to, the, electoral, registration, system, to, combat, vote, rigging, and, boost, turnout., But, in, a, written, response, to, Labour, MP, Gordon, Prentice,, the, government, said, it, would, normally, invite, observers, to, any, UK, election., Junior, constitutional, affairs, minister, Christopher, Leslie, said:, "I, fully, expect, us, to, repeat, our, previous, practice, of, doing, so, once, the, ...]
4                           [Kilroy, names, election, seat, target, Ex-chat, show, host, Robert, Kilroy-Silk, is, to, contest, the, Derbyshire, seat, of, Erewash, at, the, next, general, election., Labour's, Elizabeth, Blackman, won, the, seat, in, 1997, and, has, a, 6,932, majority., She, says, she, will, fight, on, her, record, "as, a, hard-working, constituency, MP"., Mr, Kilroy-Silk, announced, his, plans, a, day, after, launching, his, new, party,, Veritas,, the, Latin, for, truth., The, East, Midlands, MEP,, who, quit, the, UK, Independence, Party,, wants, his, new, group, to, "change, the, face", of, UK, politics., His, choice, of, election, constituency, quashes, speculation, that, he, would, stand, against, Defence, ...]
Name: tokens_basic, dtype: object

Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)

In [90]:
# Only letters, remove numbers and special characters
df['tokens_clean'] = df['Text'].apply(lambda x: re.findall(r'\b[a-zA-Z]+\b', x))
df['tokens_clean'].head()

0                                                           [Budget, to, set, scene, for, election, Gordon, Brown, will, seek, to, put, the, economy, at, the, centre, of, Labour, s, bid, for, a, third, term, in, power, when, he, delivers, his, ninth, Budget, at, GMT, He, is, expected, to, stress, the, importance, of, continued, economic, stability, with, low, unemployment, and, interest, rates, The, chancellor, is, expected, to, freeze, petrol, duty, and, raise, the, stamp, duty, threshold, from, But, the, Conservatives, and, Lib, Dems, insist, voters, face, higher, taxes, and, more, means, testing, under, Labour, Treasury, officials, have, said, there, will, not, be, a, pre, election, giveaway, but, Mr, Brown, is, ...]
1                     [Army, chiefs, in, regiments, decision, Military, chiefs, are, expected, to, meet, to, make, a, final, decision, on, the, future, of, Scotland, s, Army, regiments, A, committee, of, the, Army, Board, which, is, made, up, of, the, most, senior, defence, figures, will, discuss, plans, for, restructuring, regiments, on, Monday, The, proposals, include, cutting, Scotland, s, six, single, battalion, regiments, to, five, and, merging, these, into, a, super, regiment, The, plans, have, faced, stiff, opposition, from, campaigners, and, politicians, alike, The, committee, s, decision, must, be, ratified, by, Defence, Secretary, Geoff, Hoon, and, Prime, Minister, Tony, Blair, It, is, expected, that, it, ...]
2                                                  [Howard, denies, split, over, ID, cards, Michael, Howard, has, denied, his, shadow, cabinet, was, split, over, its, decision, to, back, controversial, Labour, plans, to, introduce, ID, cards, The, Tory, leader, said, his, front, bench, team, had, reached, a, collective, view, after, holding, a, good, discussion, but, admitted, it, was, not, an, easy, issue, He, had, decided, to, support, the, plans, as, the, police, said, they, would, help, fight, terror, crime, and, illegal, immigration, The, Lib, Dems, have, pledged, to, oppose, the, bill, when, it, is, debated, next, Monday, Tory, sources, say, senior, party, figures, had, argued, vociferously, against, the, ID, ...]
3    [Observers, to, monitor, UK, election, Ministers, will, invite, international, observers, to, check, the, forthcoming, UK, general, election, is, fairly, run, The, move, comes, amid, claims, the, poll, could, be, marred, by, electoral, fraud, A, report, by, two, MPs, committees, called, on, Thursday, for, urgent, changes, to, the, electoral, registration, system, to, combat, vote, rigging, and, boost, turnout, But, in, a, written, response, to, Labour, MP, Gordon, Prentice, the, government, said, it, would, normally, invite, observers, to, any, UK, election, Junior, constitutional, affairs, minister, Christopher, Leslie, said, I, fully, expect, us, to, repeat, our, previous, practice, of, doing, so, once, the, ...]
4                                                               [Kilroy, names, election, seat, target, Ex, chat, show, host, Robert, Kilroy, Silk, is, to, contest, the, Derbyshire, seat, of, Erewash, at, the, next, general, election, Labour, s, Elizabeth, Blackman, won, the, seat, in, and, has, a, majority, She, says, she, will, fight, on, her, record, as, a, hard, working, constituency, MP, Mr, Kilroy, Silk, announced, his, plans, a, day, after, launching, his, new, party, Veritas, the, Latin, for, truth, The, East, Midlands, MEP, who, quit, the, UK, Independence, Party, wants, his, new, group, to, change, the, face, of, UK, politics, His, choice, of, election, constituency, quashes, speculation, that, he, would, ...]
Name: tokens_clean, dtype: object

Tokenize (words with remove punctuation and all lowercase)

In [91]:
# Only letters, remove numbers and special characters
df['tokens_clean'] = df['Text'].apply(lambda x: re.findall(r'\b[a-zA-Z]+\b', x))
df['tokens_clean'].head()

0                                                           [Budget, to, set, scene, for, election, Gordon, Brown, will, seek, to, put, the, economy, at, the, centre, of, Labour, s, bid, for, a, third, term, in, power, when, he, delivers, his, ninth, Budget, at, GMT, He, is, expected, to, stress, the, importance, of, continued, economic, stability, with, low, unemployment, and, interest, rates, The, chancellor, is, expected, to, freeze, petrol, duty, and, raise, the, stamp, duty, threshold, from, But, the, Conservatives, and, Lib, Dems, insist, voters, face, higher, taxes, and, more, means, testing, under, Labour, Treasury, officials, have, said, there, will, not, be, a, pre, election, giveaway, but, Mr, Brown, is, ...]
1                     [Army, chiefs, in, regiments, decision, Military, chiefs, are, expected, to, meet, to, make, a, final, decision, on, the, future, of, Scotland, s, Army, regiments, A, committee, of, the, Army, Board, which, is, made, up, of, the, most, senior, defence, figures, will, discuss, plans, for, restructuring, regiments, on, Monday, The, proposals, include, cutting, Scotland, s, six, single, battalion, regiments, to, five, and, merging, these, into, a, super, regiment, The, plans, have, faced, stiff, opposition, from, campaigners, and, politicians, alike, The, committee, s, decision, must, be, ratified, by, Defence, Secretary, Geoff, Hoon, and, Prime, Minister, Tony, Blair, It, is, expected, that, it, ...]
2                                                  [Howard, denies, split, over, ID, cards, Michael, Howard, has, denied, his, shadow, cabinet, was, split, over, its, decision, to, back, controversial, Labour, plans, to, introduce, ID, cards, The, Tory, leader, said, his, front, bench, team, had, reached, a, collective, view, after, holding, a, good, discussion, but, admitted, it, was, not, an, easy, issue, He, had, decided, to, support, the, plans, as, the, police, said, they, would, help, fight, terror, crime, and, illegal, immigration, The, Lib, Dems, have, pledged, to, oppose, the, bill, when, it, is, debated, next, Monday, Tory, sources, say, senior, party, figures, had, argued, vociferously, against, the, ID, ...]
3    [Observers, to, monitor, UK, election, Ministers, will, invite, international, observers, to, check, the, forthcoming, UK, general, election, is, fairly, run, The, move, comes, amid, claims, the, poll, could, be, marred, by, electoral, fraud, A, report, by, two, MPs, committees, called, on, Thursday, for, urgent, changes, to, the, electoral, registration, system, to, combat, vote, rigging, and, boost, turnout, But, in, a, written, response, to, Labour, MP, Gordon, Prentice, the, government, said, it, would, normally, invite, observers, to, any, UK, election, Junior, constitutional, affairs, minister, Christopher, Leslie, said, I, fully, expect, us, to, repeat, our, previous, practice, of, doing, so, once, the, ...]
4                                                               [Kilroy, names, election, seat, target, Ex, chat, show, host, Robert, Kilroy, Silk, is, to, contest, the, Derbyshire, seat, of, Erewash, at, the, next, general, election, Labour, s, Elizabeth, Blackman, won, the, seat, in, and, has, a, majority, She, says, she, will, fight, on, her, record, as, a, hard, working, constituency, MP, Mr, Kilroy, Silk, announced, his, plans, a, day, after, launching, his, new, party, Veritas, the, Latin, for, truth, The, East, Midlands, MEP, who, quit, the, UK, Independence, Party, wants, his, new, group, to, change, the, face, of, UK, politics, His, choice, of, election, constituency, quashes, speculation, that, he, would, ...]
Name: tokens_clean, dtype: object

Tokenize (words with remove punctuation, all lowercase and remove stop words)

In [92]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# Remove stop words
df['tokens_no_stop'] = df['Text'].apply(
    lambda x: [w for w in re.findall(r'\b[a-zA-Z]+\b', x.lower()) if w not in ENGLISH_STOP_WORDS]
)
df['tokens_no_stop'].head()

0                                                                       [budget, set, scene, election, gordon, brown, seek, economy, centre, labour, s, bid, term, power, delivers, ninth, budget, gmt, expected, stress, importance, continued, economic, stability, low, unemployment, rates, chancellor, expected, freeze, petrol, duty, raise, stamp, duty, threshold, conservatives, lib, dems, insist, voters, face, higher, taxes, means, testing, labour, treasury, officials, said, pre, election, giveaway, mr, brown, thought, spare, increase, stamp, duty, threshold, freeze, petrol, duty, extension, tax, credit, scheme, poorer, families, possible, help, pensioners, stamp, duty, threshold, rise, intended, help, time, buyers, likely, theme, main, parties, general, election, manifestos, years, ago, buyers, greater, chance, avoiding, stamp, duty, close, half, million, properties, ...]
1         [army, chiefs, regiments, decision, military, chiefs, expected, meet, make, final, decision, future, scotland, s, army, regiments, committee, army, board, senior, defence, figures, discuss, plans, restructuring, regiments, monday, proposals, include, cutting, scotland, s, single, battalion, regiments, merging, super, regiment, plans, faced, stiff, opposition, campaigners, politicians, alike, committee, s, decision, ratified, defence, secretary, geoff, hoon, prime, minister, tony, blair, expected, public, week, ministers, announced, reorganisation, army, drew, question, mark, futures, black, watch, kings, scottish, borderers, royal, scots, royal, highland, fusiliers, argyll, sutherland, highlanders, october, council, scottish, colonels, proposed, merger, royal, scots, king, s, scottish, borderers, single, battalion, vision, new, super, regiment, proposals, ...]
2                                                                                            [howard, denies, split, id, cards, michael, howard, denied, shadow, cabinet, split, decision, controversial, labour, plans, introduce, id, cards, tory, leader, said, bench, team, reached, collective, view, holding, good, discussion, admitted, easy, issue, decided, support, plans, police, said, help, fight, terror, crime, illegal, immigration, lib, dems, pledged, oppose, debated, monday, tory, sources, say, senior, party, figures, argued, vociferously, id, card, scheme, reported, reservations, strategy, senior, shadow, cabinet, members, david, davis, oliver, letwin, tim, yeo, mr, howard, denied, mr, yeo, transport, environment, spokesman, said, plans, stink, said, confident, shadow, home, secretary, mr, davis, set, position, clearly, stands, debate, matter, week, mr, howard, ...]
3    [observers, monitor, uk, election, ministers, invite, international, observers, check, forthcoming, uk, general, election, fairly, run, comes, amid, claims, poll, marred, electoral, fraud, report, mps, committees, called, thursday, urgent, changes, electoral, registration, combat, vote, rigging, boost, turnout, written, response, labour, mp, gordon, prentice, government, said, normally, invite, observers, uk, election, junior, constitutional, affairs, minister, christopher, leslie, said, fully, expect, repeat, previous, practice, doing, date, general, election, announced, government, looked, ways, boosting, voter, turnout, fell, general, election, trial, postal, ballots, english, regions, summer, hit, delays, fraud, allegations, liberal, democrat, peer, lord, greaves, called, week, international, observers, general, election, saying, months, court, challenges, ...]
4                                                                                                    [kilroy, names, election, seat, target, ex, chat, host, robert, kilroy, silk, contest, derbyshire, seat, erewash, general, election, labour, s, elizabeth, blackman, won, seat, majority, says, fight, record, hard, working, constituency, mp, mr, kilroy, silk, announced, plans, day, launching, new, party, veritas, latin, truth, east, midlands, mep, quit, uk, independence, party, wants, new, group, change, face, uk, politics, choice, election, constituency, quashes, speculation, stand, defence, secretary, geoff, hoon, ashfield, nottinghamshire, ukip, won, vote, erewash, june, s, european, elections, mr, kilroy, silk, candidates, region, erewash, held, tories, ms, blackman, said, proud, government, s, achievements, area, declined, view, mr, kilroy, silk, point, thursday, ...]
Name: tokens_no_stop, dtype: object

Tokenize (words with remove punctuation, all lowercase and  remove stop words, with speech_tagging)

In [93]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('tagsets')

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import re

def tokenize_pos(text):
    words = [w for w in re.findall(r'\b[a-zA-Z]+\b', text.lower()) if w not in ENGLISH_STOP_WORDS]
    return nltk.pos_tag(words)

df['tokens_pos'] = df['Text'].apply(tokenize_pos)
df['tokens_pos'].head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

0                                                                              [(budget, NN), (set, VBN), (scene, NN), (election, NN), (gordon, VBD), (brown, JJ), (seek, JJ), (economy, NN), (centre, VBP), (labour, JJ), (s, NN), (bid, NN), (term, NN), (power, NN), (delivers, NNS), (ninth, JJ), (budget, NN), (gmt, NN), (expected, VBN), (stress, NN), (importance, NN), (continued, VBD), (economic, JJ), (stability, NN), (low, JJ), (unemployment, NN), (rates, NNS), (chancellor, VBP), (expected, VBN), (freeze, NN), (petrol, NN), (duty, NN), (raise, NN), (stamp, NN), (duty, NN), (threshold, JJ), (conservatives, NNS), (lib, VBP), (dems, NNS), (insist, VBP), (voters, NNS), (face, VBP), (higher, JJR), (taxes, NNS), (means, VBZ), (testing, VBG), (labour, JJ), (treasury, NN), (officials, NNS), (said, VBD), (pre, JJ), (election, NN), (giveaway, NN), (mr, VBD), (brown, JJ), (thought, NN), (spare, JJ), (increase, NN), (stamp, NN), (duty, NN), (threshold, NN), (freeze, NN), (petrol, NN), (duty, NN), (extension, NN), (tax, NN), (credit, NN), (scheme, NN), (poorer, NN), (families, NNS), (possible, JJ), (help, NN), (pensioners, NNS), (stamp, VBP), (duty, NN), (threshold, JJ), (rise, NN), (intended, VBN), (help, NN), (time, NN), (buyers, NNS), (likely, JJ), (theme, JJ), (main, JJ), (parties, NNS), (general, JJ), (election, NN), (manifestos, CD), (years, NNS), (ago, IN), (buyers, NNS), (greater, JJR), (chance, NN), (avoiding, VBG), (stamp, JJ), (duty, NN), (close, JJ), (half, NN), (million, CD), (properties, NNS), ...]
1        [(army, NN), (chiefs, NN), (regiments, NNS), (decision, NN), (military, JJ), (chiefs, NNS), (expected, VBD), (meet, RB), (make, JJ), (final, JJ), (decision, NN), (future, NN), (scotland, VBP), (s, JJ), (army, NN), (regiments, NNS), (committee, NN), (army, VBP), (board, NN), (senior, JJ), (defence, NN), (figures, NNS), (discuss, VBP), (plans, NNS), (restructuring, VBG), (regiments, NNS), (monday, JJ), (proposals, NNS), (include, VBP), (cutting, VBG), (scotland, NN), (s, JJ), (single, JJ), (battalion, NN), (regiments, NNS), (merging, VBG), (super, JJ), (regiment, NN), (plans, NNS), (faced, VBD), (stiff, JJ), (opposition, NN), (campaigners, NNS), (politicians, NNS), (alike, RB), (committee, NN), (s, JJ), (decision, NN), (ratified, VBD), (defence, NN), (secretary, NN), (geoff, NN), (hoon, NN), (prime, JJ), (minister, NN), (tony, NN), (blair, NN), (expected, VBN), (public, JJ), (week, NN), (ministers, NNS), (announced, VBD), (reorganisation, NN), (army, NN), (drew, VBD), (question, NN), (mark, NN), (futures, NNS), (black, JJ), (watch, VBP), (kings, NNS), (scottish, JJ), (borderers, NNS), (royal, VBP), (scots, NNS), (royal, JJ), (highland, NN), (fusiliers, NNS), (argyll, VBP), (sutherland, NN), (highlanders, NNS), (october, VBP), (council, JJ), (scottish, JJ), (colonels, NNS), (proposed, VBN), (merger, NN), (royal, JJ), (scots, NNS), (king, VBG), (s, JJ), (scottish, JJ), (borderers, NNS), (single, JJ), (battalion, NN), (vision, NN), (new, JJ), (super, JJ), (regiment, NN), (proposals, NNS), ...]
2                                                                                                    [(howard, NN), (denies, VBZ), (split, VBN), (id, JJ), (cards, NNS), (michael, FW), (howard, RB), (denied, VBD), (shadow, JJ), (cabinet, NN), (split, NN), (decision, NN), (controversial, JJ), (labour, NN), (plans, NNS), (introduce, VBP), (id, JJ), (cards, NNS), (tory, JJ), (leader, NN), (said, VBD), (bench, JJ), (team, NN), (reached, VBD), (collective, JJ), (view, NN), (holding, VBG), (good, JJ), (discussion, NN), (admitted, VBD), (easy, JJ), (issue, NN), (decided, VBD), (support, NN), (plans, NNS), (police, NN), (said, VBD), (help, NN), (fight, NN), (terror, NN), (crime, NN), (illegal, JJ), (immigration, NN), (lib, NN), (dems, VBZ), (pledged, VBN), (oppose, RB), (debated, VBN), (monday, JJ), (tory, JJ), (sources, NNS), (say, VBP), (senior, JJ), (party, NN), (figures, NNS), (argued, VBD), (vociferously, RB), (id, JJ), (card, NN), (scheme, NN), (reported, VBD), (reservations, NNS), (strategy, NN), (senior, JJ), (shadow, JJ), (cabinet, NN), (members, NNS), (david, VBP), (davis, JJ), (oliver, IN), (letwin, JJ), (tim, NN), (yeo, NN), (mr, FW), (howard, NN), (denied, VBD), (mr, NN), (yeo, NN), (transport, NN), (environment, NN), (spokesman, NN), (said, VBD), (plans, NNS), (stink, VBP), (said, VBD), (confident, JJ), (shadow, NN), (home, NN), (secretary, NN), (mr, NN), (davis, NN), (set, VBN), (position, NN), (clearly, RB), (stands, VBZ), (debate, JJ), (matter, NN), (week, NN), (mr, FW), (howard, NN), ...]
3    [(observers, NNS), (monitor, VBP), (uk, JJ), (election, NN), (ministers, NNS), (invite, VBP), (international, JJ), (observers, NNS), (check, VBP), (forthcoming, VBG), (uk, JJ), (general, JJ), (election, NN), (fairly, RB), (run, VBN), (comes, VBZ), (amid, IN), (claims, NNS), (poll, VBP), (marred, JJ), (electoral, JJ), (fraud, NN), (report, NN), (mps, NNS), (committees, NNS), (called, VBD), (thursday, JJ), (urgent, JJ), (changes, NNS), (electoral, JJ), (registration, NN), (combat, NN), (vote, NN), (rigging, VBG), (boost, NN), (turnout, NN), (written, VBN), (response, NN), (labour, NN), (mp, NN), (gordon, NN), (prentice, JJ), (government, NN), (said, VBD), (normally, RB), (invite, JJ), (observers, NNS), (uk, JJ), (election, NN), (junior, JJ), (constitutional, JJ), (affairs, NNS), (minister, NN), (christopher, NN), (leslie, NN), (said, VBD), (fully, RB), (expect, JJ), (repeat, NN), (previous, JJ), (practice, NN), (doing, VBG), (date, NN), (general, JJ), (election, NN), (announced, VBD), (government, NN), (looked, VBD), (ways, NNS), (boosting, VBG), (voter, NN), (turnout, NN), (fell, VBD), (general, JJ), (election, NN), (trial, NN), (postal, JJ), (ballots, NNS), (english, JJ), (regions, NNS), (summer, NN), (hit, VBP), (delays, NNS), (fraud, NN), (allegations, NNS), (liberal, JJ), (democrat, NNS), (peer, VBP), (lord, NN), (greaves, NNS), (called, VBD), (week, NN), (international, JJ), (observers, NNS), (general, JJ), (election, NN), (saying, VBG), (months, NNS), (court, NN), (challenges, VBZ), ...]
4                                                                                                               [(kilroy, NN), (names, NNS), (election, NN), (seat, NN), (target, NN), (ex, VBZ), (chat, WP), (host, NN), (robert, NN), (kilroy, NNP), (silk, NN), (contest, NN), (derbyshire, NN), (seat, NN), (erewash, JJ), (general, JJ), (election, NN), (labour, NN), (s, NN), (elizabeth, VBZ), (blackman, JJ), (won, VBD), (seat, JJ), (majority, NN), (says, VBZ), (fight, NN), (record, NN), (hard, NN), (working, VBG), (constituency, NN), (mp, FW), (mr, NN), (kilroy, FW), (silk, NN), (announced, VBD), (plans, NNS), (day, NN), (launching, VBG), (new, JJ), (party, NN), (veritas, NNS), (latin, JJ), (truth, NN), (east, JJ), (midlands, NNS), (mep, VBP), (quit, NN), (uk, JJ), (independence, NN), (party, NN), (wants, VBZ), (new, JJ), (group, NN), (change, NN), (face, NN), (uk, JJ), (politics, NNS), (choice, NN), (election, NN), (constituency, NN), (quashes, NNS), (speculation, NN), (stand, VBP), (defence, NN), (secretary, NN), (geoff, NN), (hoon, NN), (ashfield, VBD), (nottinghamshire, JJ), (ukip, JJ), (won, VBD), (vote, NN), (erewash, NN), (june, NN), (s, JJ), (european, JJ), (elections, NNS), (mr, VBP), (kilroy, JJ), (silk, NN), (candidates, NNS), (region, NN), (erewash, VBP), (held, VBN), (tories, NNS), (ms, RBR), (blackman, NN), (said, VBD), (proud, JJ), (government, NN), (s, NN), (achievements, NNS), (area, NN), (declined, VBD), (view, NN), (mr, NN), (kilroy, NN), (silk, NN), (point, NN), (thursday, NN), ...]
Name: tokens_pos, dtype: object

***In the different tokenization process it transforms the text into different bits and keeps only the important or relevent text data. This lessens the noise and even computational strain when performing analysis or training on the text data. With tokenizaion we are able to extract important text data only.***

## * Compare the similar document using Count Vector & Using TF-IDF Vectorizer
## * Use the cosine similarity to measure the similarity of text

Count Vector

In [94]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')  # remove stop words
X_count = cv.fit_transform(df['Text'])
X_count_array = X_count.toarray()

In [95]:
import pandas as pd

# Rows = documents, Columns = words
dt_count = pd.DataFrame(
    X_count_array,
    columns=cv.get_feature_names_out(),
    index=df.index
)

dt_count.head()

,00,000,0001,000bn,000m,000s,000th,001,001and,001st,...,zooms,zooropa,zornotza,zorro,zubair,zuluaga,zurich,zutons,zvonareva,zvyagintsev
0,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
from sklearn.metrics.pairwise import cosine_similarity

# first two rows
vec1 = X_count_array[0]
vec2 = X_count_array[1]

similarity = cosine_similarity([vec1], [vec2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.12290517471386482

In [97]:
from sklearn.metrics.pairwise import cosine_similarity

# first two rows
vec1 = X_count_array[0]
vec2 = X_count_array[4]

similarity = cosine_similarity([vec1], [vec2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.18853795635981851

In [98]:
from sklearn.metrics.pairwise import cosine_similarity

# first two rows
vec1 = X_count_array[0]
vec2 = X_count_array[3]

similarity = cosine_similarity([vec1], [vec2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.24950073428377825

<b><i>Out of all the tests the 4th data point has the highest similarity on the first text.

TF-IDF

In [99]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(df['Text']).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(df['Text'])

In [100]:
doc1 = dt_tfidf.iloc[0].values
doc2 = dt_tfidf.iloc[1].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([doc1], [doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.03439323924619003

In [101]:
doc1 = dt_tfidf.iloc[0].values
doc2 = dt_tfidf.iloc[4].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([doc1], [doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.05605676355389688

In [102]:
doc1 = dt_tfidf.iloc[0].values
doc2 = dt_tfidf.iloc[3].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([doc1], [doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.07949829067555755

<b><i>Now in Using the TF-IDF the similarity score a very low compared to the comparison made using the Count Vector.

# Now I will use the tokenized Data

## Counter Vector

In [103]:
# tokens_no_stop
df['tokens_no_words'] = df['tokens_no_stop'].apply(lambda x: " ".join(x))
df['tokens_no_words'].head()

0                                                        budget set scene election gordon brown seek economy centre labour s bid term power delivers ninth budget gmt expected stress importance continued economic stability low unemployment rates chancellor expected freeze petrol duty raise stamp duty threshold conservatives lib dems insist voters face higher taxes means testing labour treasury officials said pre election giveaway mr brown thought spare increase stamp duty threshold freeze petrol duty extension tax credit scheme poorer families possible help pensioners stamp duty threshold rise intended help time buyers likely theme main parties general election manifestos years ago buyers greater chance avoiding stamp duty close half million properties england wales selling average uk property prices doubled starting threshold stamp duty increased tax credits result number properties incurring stamp duty rocketed government s tax liberal democrats unveiled proposals raise stamp duty threshold february tories thought likely propose increased thresholds shadow chancellor oliver letwin branding stamp duty classic labour stealth tax tories say chancellor gives away clawed higher taxes labour returned power shadow treasury chief secretary george osborne said looks british economy moment says sharp deterioration public finances black hole said labour elected substantial tax increase budget election order mr brown s advisor ed balls parliamentary hopeful said examination tory plans economy showed difference investment end parliament main parties added don t accept need changes plans set meet spending commitments lib dems david laws said chancellor doubt tell today wonderfully economy doing said lot built increase personal consumer debt years makes economy quite vulnerable potentially rates significant way snp leader alex salmond said party introduce grant time buyers reduce corporation tax introduce citizens pension free means testing plaid cymru s economics spokesman adam price said wanted help people housing ladder increase minimum wage hour
1                                                                                                army chiefs regiments decision military chiefs expected meet make final decision future scotland s army regiments committee army board senior defence figures discuss plans restructuring regiments monday proposals include cutting scotland s single battalion regiments merging super regiment plans faced stiff opposition campaigners politicians alike committee s decision ratified defence secretary geoff hoon prime minister tony blair expected public week ministers announced reorganisation army drew question mark futures black watch kings scottish borderers royal scots royal highland fusiliers argyll sutherland highlanders october council scottish colonels proposed merger royal scots king s scottish borderers single battalion vision new super regiment proposals merge amalgamate regiments super regiment sparked political outcry labour backbenchers opposition politicians opposing plan felt timing insensitive black watch frontline iraq suffering casualties save scottish regiments campaigners angered threatened stand labour general election speaking ahead expected army board meeting spokesman said government army board spent past months attempting trick serving soldiers public thinking planned changes scottish regiments good army serving soldier good destroy scotland s regiments moulding single super regiment lead severe recruitment problems loss local connections regiments loss scotland important heritage importantly future regiments envy armies world alternative blueprint forward labour mp eric joyce proposed going ahead merger preserving regiments brief time speculation prime minister consider plan unlikely speaking scotland week mr blair said aim preserve tradition introduce effective structure hinted super regiment likely said don t want rid history traditions regiment local connections far want make sure transfer people easily regiments deploy flexibly prime minister said hoped campaigners concerns taken account need effective change paramount
2                                                                                          howard denies split id cards michael howard denied shadow cabinet split decision controversial labour plans introduce id cards tory leader said bench team reached collective view holding good discussion admitted easy issue decided support plans police said help fight terror crime illegal immigration lib dems pledged oppose debated monday tory sources say senior party figures argued vociferously id card scheme reported reservations strategy senior shadow cabinet members david davis oliver letwin tim yeo mr howard denied mr yeo transport environment spokesman said plans stink said confident shadow home secretary mr davis set position clearly stands debate matter week mr howard said police said id cards help foil terror bomb plot people lose lives added police say seriously acknowledged good libertarian arguments cards said shadow cabinet weighed conflicting interests reaching decision don t pretend easy decision end day decision taken denied afraid looking soft issue compared labour conservatives announced support government plans monday evening sources party told bbc mr howard favour id cards tried introduce home secretary tories insisted hold ministers account precise purpose scheme said press labour objectives met home office able deliver pledged assess cost effectiveness id cards people s privacy properly protected important remember decade come effect spokesman said lib dem home affairs spokesman mark oaten branded id scheme waste money deeply flawed said signs michael howard overruling colleagues concerns id cards chairman bar council guy mansfield qc warned real risk people margins society driven hands extremists going happen young asian men bomb gone going stopped haven t id cards going detained tory ex minister douglas hogg said opposed plans id cards branding regressive step intrude lives ordinary citizens counterbalancing benefits predicted ultimately carrying cards compulsory lead large numbers britain s ethnic minorities stopped police
3    observers monitor uk election ministers invite international observers check forthcoming uk general election fairly run comes amid claims poll marred electoral fraud report mps committees called thursday urgent changes electoral registration combat vote rigging boost turnout written response labour mp gordon prentice government said normally invite observers uk election junior constitutional affairs minister christopher leslie said fully expect repeat previous practice doing date general election announced government looked ways boosting voter turnout fell general election trial postal ballots english regions summer hit delays fraud allegations liberal democrat peer lord greaves called week international observers general election saying months court challenges scale seen century thursday s report drawn committees scrutinising work office deputy prime minister odpm department constitutional affairs dca said growth postal voting strong case tighten fraud protection requiring voters register individually household said million people eligible vote registered figures general election suggest people aged black voters electoral roll young people shared accommodation thought miss acts head household form odpm committee chairman andrew bennett said individual voter registration opposed registration household quickly introduced dramatically reduce chances fraud counterpart dca committee alan beith said delayed measures likely increase registration place proved effective shadow constitutional affairs secretary oliver heald accused government dragging feet badly needed measure vital ahead northern ireland individual electoral registration safeguard integrity britain s electoral said report said individual registration treated carefully voters disappeared electoral roll northern ireland introduced report said government consider fines unregistered voters accepted experts said expensive hard enforce said incentives register council tax rebate likely seen gimmicks risked undermining integrity mps said instead called imaginative campaigns boost
4                                                                                                                                                                                                                                                                                                                                          kilroy names election seat target ex chat host robert kilroy silk contest derbyshire seat erewash general election labour s elizabeth blackman won seat majority says fight record hard working constituency mp mr kilroy silk announced plans day launching new party veritas latin truth east midlands mep quit uk independence party wants new group change face uk politics choice election constituency quashes speculation stand defence secretary geoff hoon ashfield nottinghamshire ukip won vote erewash june s european elections mr kilroy silk candidates region erewash held tories ms blackman said proud government s achievements area declined view mr kilroy silk point thursday told london news conference veritas avoid old parties lies spin said country stolen mass immigration promised firm fair policy immigration veritas says hopes contest seats forthcoming general election plans announce detailed policies crime tax pensions health defence weeks ukip leader roger knapman says glad mr kilroy silk labour campaign spokesman fraser kemp said veritas joining crowded field right british politics mr kilroy silk joined new venture ukip s london assembly members damien hockney veritas deputy leader ukip s chairman petrina holdsworth said group just parody party men left mr kilroy silk quit ukip week months tension vied unsuccessfully leadership party said ashamed member ukip leadership gone awol great opportunity offered place june s european elections ukip s leader roger knapman said glad mr kilroy silk remarkable ability influence people sadly european election clear interested robert kilroy silk party uk independence party nice knowing goodbye said ukip officials argue mr kilroy silk straightforward attacking party wanted lead
Name: tokens_no_words, dtype: object

In [104]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')  # remove stop words
X_count = cv.fit_transform(df['tokens_no_words'])
X_count_array = X_count.toarray()

dt_count = pd.DataFrame(
    X_count_array,
    columns=cv.get_feature_names_out(),
    index=df.index
)

In [105]:
from sklearn.metrics.pairwise import cosine_similarity


docc1 = X_count_array[0]
docc2 = X_count_array[1]

similarity = cosine_similarity([docc1], [docc2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.12696486968067888

In [106]:
from sklearn.metrics.pairwise import cosine_similarity

# first two rows
docc1 = X_count_array[0]
docc2 = X_count_array[4]

similarity = cosine_similarity([docc1], [docc2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.19565001644302182

In [107]:
from sklearn.metrics.pairwise import cosine_similarity

# first two rows
docc1 = X_count_array[0]
docc2 = X_count_array[3]

similarity = cosine_similarity([docc1], [docc2])[0][0]
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.2602680122054848

## TF IDF Vectorizer

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(df['tokens_no_words']).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(df['tokens_no_words'])

In [109]:
new_doc1 = dt_tfidf.iloc[0].values
new_doc2 = dt_tfidf.iloc[1].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([new_doc1], [new_doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.03516146095222442

In [110]:
new_doc1 = dt_tfidf.iloc[0].values
new_doc2 = dt_tfidf.iloc[4].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([new_doc1], [new_doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.05762007351774737

In [111]:
new_doc1 = dt_tfidf.iloc[0].values
new_doc2 = dt_tfidf.iloc[3].values

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([new_doc1], [new_doc2])[0][0]
print("Cosine Similarity", similarity)

Cosine Similarity 0.08203634344684455

***After doing the cosine similarity on the tokenized data and comparing it to the raw text data I observed that there is only minimal diference in both the Count Vector and TF-IDF. I think that this dataset even if the text are in the same classification have only small similarity.***

#### Conclusion

<b><i>After performing this activity I was able to learn about the preprocessing techniques when handling text data. I learned about the usage of regex in performing tokenization in which I was able to cut the data by removing unnecessary text such as symbols, punctuations, and stop words. Then I was able to utilize two techniques for text transformation which is the Count vector and TF-IDF Vectorizer in which I was able to observe that TF-IDF vectorizer is better in extracting important weights for each tokens which results into finding unique similarities in the dataset. After learning these concepts, I applied them in a text dataset which has different classifications and I observed that TF-IDF has lower similarity scores than Count Vector. Overall, this activity helped me learn about performing text similarity analysis on a dataset.